### ISSUE TITLE
not seeing english titles

### ISSUE THREAD

**Issue by rickyray9** [Animorphs/MAL-English-Titles#11]
<h3>Fill out **all** of the following fields:</h3>

**Describe the bug**
script installed with tampermonkey and extension is enabled, but not seeing english titles

**Expected behavior**
Navigate to https://myanimelist.net/ and see english titles on anime where they are available. 

**How To Reproduce**
1. Go to https://myanimelist.net/
2. Click on anime
3. Scroll down to top anime

**Screenshots**
https://i.imgur.com/ERHy5R4.png

**PC**
 - OS: Windows
 - Browser Chrome

**Comment by Animorphs** [comment]
Thanks, noticed this a while ago and fixed it, but forgot to push it.
Should be working now (be139851ec88b25d9768194d4e5ed42a6cdabedc), although you might have to wait a little bit for it to update on your end.
