### ISSUE TITLE
[Bug] English titles do not appear bold in the seasonal page

### ISSUE THREAD

**Issue by SacredZenpie** [Animorphs/MAL-English-Titles#13]
Bug: The English title text is not bold as it is on the other parts of MAL.

![image](https://github.com/Animorphs/MAL-English-Titles/assets/110957549/c83bbcb4-26a7-43a5-b107-77af61f8157d)

**PC**
 - OS: Windows 10 22H2
 - Browser: Firefox (latest beta)

**Comment by Animorphs** [comment]
Thanks for the report.

With this particular section, this is intended, as it's mostly just copying the format that MAL uses when you're logged out (and not using my script). Additionally, applying `style="font-weight:bold"` here doesn't actually seem to work; not sure why, but something I'm not interested in solving as it works fine as is.

I will however update my screenshots in the readme soon, so it's reflective of the change.
