### ISSUE TITLE
[Feature Request] Add 'recommendation pages' to list of supported pages

### ISSUE THREAD

**Issue by theorist-complex** [Animorphs/MAL-English-Titles#15]
No idea if its possible or not, but I would like to see the "Recommendation Page" added to the list of supported pages. I find myself wanting English titles the most on search pages and the rec pages. Search page already works well, but would also like to see the rec page added also.

I guess its not a huge deal, as I can always click through to the main page, but it definitely gets a little frustrating having to click through each time just to see what the anime title is, especially when Im going on a hunt for future shows to watch.

Thanks either way; I love your work on this!

**Comment by Animorphs** [comment]
Added 👍 https://github.com/Animorphs/MAL-English-Titles/commit/25103aac29ff03aed036d1f43d5248cfbb02e5a7

**Comment by theorist-complex** [comment]
> Added 👍 [25103aa](https://github.com/Animorphs/MAL-English-Titles/commit/25103aac29ff03aed036d1f43d5248cfbb02e5a7)

Works great! Thanks a lot for taking the time to add this, I really appreciate it!
