### ISSUE TITLE
[Bug] Animelist only translates first 150 results

### ISSUE THREAD

**Issue by Animorphs** [Animorphs/MAL-English-Titles#6]
<h3>Fill out **all** of the following fields:</h3>

**Describe the bug**
When accessing a users animelist or mangalist with more than 150 results, only the first 150 results will have translations, at least until you scroll to the end of currently displayed, which refreshes the event listener and then backfills everything in.

**Expected behavior**
All visible results should be filled in.

**How To Reproduce**
1. Go to any list with >150 results, e.g. myanimelist.net/animelist/Animorphs
2. Scroll down post 150
4. See lack of translations

**Screenshots**
https://i.imgur.com/WrceYls.png

**PC**
 - OS: Windows
 - Browser: Chrome

**Extra (optional)**
Haven't really investigated why it does this, probably only loads 150 at start? Can probably add a listener or something, but not sure why current listener isn't picking it up.

**Comment by nicegamer7** [comment]
You're ahead of me 😁. I had this issue drafted, just didn't submit it yet.

I have an idea for a fix, just haven't gotten around to trying it. The idea is to use a MutationObserver rather than the current listener.
