### ISSUE TITLE
[Feature Request] Please add an option to display the original Japanese title.

### ISSUE THREAD

**Issue by onedayakub** [Animorphs/MAL-English-Titles#8]
**Is your feature request related to a problem? Please describe.**
Please add an option to display the original Japanese title.

**Describe the solution you'd like**
ex)Attack on Titan->進撃の巨人

**Describe alternatives you've considered**

**Extra**

**Comment by Animorphs** [comment]
Apologies but I currently have no plan for this as I'm not interested in the Kanji. 
You can however use [this one that someone else has created](https://github.com/Jorengarenar/UserScripts/raw/master/MyAnimeList/Japanese_Titles.user.js). It's not as sophisticated as mine but will hopefully cover what you're after.
