### ISSUE TITLE
[Bug] No translations showing anywhere

### ISSUE THREAD

**Issue by SentaiBrad** [Animorphs/MAL-English-Titles#9]
**PC**
 - OS: W11
 - Firefox 101.0.1

I would fill out all of the info, but I simply do not see ANY translations with or without the official setting enabled. I'm using Greasemonkey, I disabled all other scripts that were running on MAL, and I even turned off uBlock origin. 

Any info I can get for you that would help in such a broad issue?

Edit: Oops, forgot the title and I can't edit the title now.

**Comment by Animorphs** [comment]
Hello, this does not work with Greasemonkey (per the "[💻 How to Install](https://github.com/Animorphs/MAL-English-Titles#-how-to-install-)" section), so please give it a go with [Tampermonkey ](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/) instead!
